language: go
go:
  # test with the two most recent Go versions
  - 1.12.x
  - 1.13.x
env:
  - GOARCH=amd64
  - GOARCH=386
sudo: false
go_import_path: github.com/nsqio/nsq
before_install:
  - go get github.com/mattn/goveralls
script:
  - ./travis.sh
notifications:
  email: false
